#pragma once

#define FG_BLACK   "\e[0;30m"
#define FG_RED     "\e[0;31m"
#define FG_GREEN   "\e[0;32m"
#define FG_YELLOW  "\e[0;33m"
#define FG_BLUE    "\e[0;34m"
#define FG_MAGENTA "\e[0;35m"
#define FG_CYAN    "\e[0;36m"
#define FG_WHITE   "\e[0;37m"

#define BFG_BLACK   "\e[1;30m"
#define BFG_RED     "\e[1;31m"
#define BFG_GREEN   "\e[1;32m"
#define BFG_YELLOW  "\e[1;33m"
#define BFG_BLUE    "\e[1;34m"
#define BFG_MAGENTA "\e[1;35m"
#define BFG_CYAN    "\e[1;36m"
#define BFG_WHITE   "\e[1;37m"

#define BG_BLACK   "\e[40m"
#define BG_RED     "\e[41m"
#define BG_GREEN   "\e[42m"
#define BG_YELLOW  "\e[43m"
#define BG_BLUE    "\e[44m"
#define BG_MAGENTA "\e[45m"
#define BG_CYAN    "\e[46m"
#define BG_WHITE   "\e[47m"

#define END "\e[0m"
