#pragma once

#include <SDL3/SDL.h>

enum KeyCode
{
    // Letters
    A            = SDLK_A,
    B            = SDLK_B,
    C            = SDLK_C,
    D            = SDLK_D,
    E            = SDLK_E,
    F            = SDLK_F,
    G            = SDLK_G,
    H            = SDLK_H,
    I            = SDLK_I,
    J            = SDLK_J,
    K            = SDLK_K,
    L            = SDLK_L,
    M            = SDLK_M,
    N            = SDLK_N,
    O            = SDLK_O,
    P            = SDLK_P,
    Q            = SDLK_Q,
    R            = SDLK_R,
    S            = SDLK_S,
    T            = SDLK_T,
    U            = SDLK_U,
    V            = SDLK_V,
    W            = SDLK_W,
    X            = SDLK_X,
    Y            = SDLK_Y,
    V            = SDLK_V,
    W            = SDLK_W,
    X            = SDLK_X,
    Y            = SDLK_Y,
    Z            = SDLK_Z,
    // Number row
    One          = SDLK_1,
    Two          = SDLK_2,
    Three        = SDLK_3,
    Four         = SDLK_4,
    Five         = SDLK_5,
    Six          = SDLK_6,
    Seven        = SDLK_7,
    Eight        = SDLK_8,
    Nine         = SDLK_9,
    Zero         = SDLK_0,
    // F-row
    F1           = SDLK_F1,
    F2           = SDLK_F2,
    F3           = SDLK_F3,
    F4           = SDLK_F4,
    F5           = SDLK_F5,
    F6           = SDLK_F6,
    F7           = SDLK_F7,
    F8           = SDLK_F8,
    F9           = SDLK_F9,
    F10          = SDLK_F10,
    F11          = SDLK_F11,
    F12          = SDLK_F12,
    // Modifiers
    Return       = SDLK_RETURN,
    Esc          = SDLK_ESCAPE,
    Backspace    = SDLK_BACKSPACE,
    Tab          = SDLK_TAB,
    Space        = SDLK_SPACE,
    PrintScreen  = SDLK_PRINTSCREEN,
    ScrollLock   = SDLK_SCROLLLOCK,
    Pause        = SDLK_PAUSE,
    Insert       = SDLK_INSERT,
    Home         = SDLK_HOME,
    PageUp       = SDLK_PAGEUP,
    PageDown     = SDLK_PAGEDOWN,
    Delete       = SDLK_DELETE,
    End          = SDLK_END,
    Right        = SDLK_RIGHT,
    Left         = SDLK_LEFT,
    Down         = SDLK_DOWN,
    Up           = SDLK_UP,
    Minus        = SDLK_MINUS,
    Equals       = SDLK_EQUALS,
    LeftBracket  = SDLK_LEFTBRACKET,
    RightBracket = SDLK_RIGHTBRACKET,
    BackSlash    = SDLK_BACKSLASH,
    SemiColon    = SDLK_SEMICOLON,
    Apostrophe   = SDLK_APOSTROPHE,
    Grave        = SDLK_GRAVE,
    Comma        = SDLK_COMMA,
    Period       = SDLK_PERIOD,
    Slash        = SDLK_SLASH,
    Capslock     = SDLK_CAPSLOCK,
    // Numpad
    NumLock      = SDLK_NUMLOCKCLEAR,
    NumDivide    = SDLK_KP_DIVIDE,
    NumMultiply  = SDLK_KP_MULTIPLY,
    NumMinus     = SDLK_KP_MINUS,
    NumPlus      = SDLK_KP_PLUS,
    NumEnter     = SDLK_KP_ENTER,
    NumOne       = SDLK_KP_1,
    NumTwo       = SDLK_KP_2,
    NumThree     = SDLK_KP_3,
    NumFour      = SDLK_KP_4,
    NumFive      = SDLK_KP_5,
    NumSix       = SDLK_KP_6,
    NumSeven     = SDLK_KP_7,
    NumEight     = SDLK_KP_8,
    NumNine      = SDLK_KP_9,
    NumZero      = SDLK_KP_0,
    NumPeriod    = SDLK_KP_PERIOD
};
