#pragma once

#include <SDL3/SDL.h>

typedef enum
{
    // Letters
    KeyCode_A            = SDLK_A,
    KeyCode_B            = SDLK_B,
    KeyCode_C            = SDLK_C,
    KeyCode_D            = SDLK_D,
    KeyCode_E            = SDLK_E,
    KeyCode_F            = SDLK_F,
    KeyCode_G            = SDLK_G,
    KeyCode_H            = SDLK_H,
    KeyCode_I            = SDLK_I,
    KeyCode_J            = SDLK_J,
    KeyCode_K            = SDLK_K,
    KeyCode_L            = SDLK_L,
    KeyCode_M            = SDLK_M,
    KeyCode_N            = SDLK_N,
    KeyCode_O            = SDLK_O,
    KeyCode_P            = SDLK_P,
    KeyCode_Q            = SDLK_Q,
    KeyCode_R            = SDLK_R,
    KeyCode_S            = SDLK_S,
    KeyCode_T            = SDLK_T,
    KeyCode_U            = SDLK_U,
    KeyCode_V            = SDLK_V,
    KeyCode_W            = SDLK_W,
    KeyCode_X            = SDLK_X,
    KeyCode_Y            = SDLK_Y,
    KeyCode_Z            = SDLK_Z,
    // Number row
    KeyCode_1            = SDLK_1,
    KeyCode_2            = SDLK_2,
    KeyCode_3            = SDLK_3,
    KeyCode_4            = SDLK_4,
    KeyCode_5            = SDLK_5,
    KeyCode_6            = SDLK_6,
    KeyCode_7            = SDLK_7,
    KeyCode_8            = SDLK_8,
    KeyCode_9            = SDLK_9,
    KeyCode_0            = SDLK_0,
    // F-row
    KeyCode_F1           = SDLK_F1,
    KeyCode_F2           = SDLK_F2,
    KeyCode_F3           = SDLK_F3,
    KeyCode_F4           = SDLK_F4,
    KeyCode_F5           = SDLK_F5,
    KeyCode_F6           = SDLK_F6,
    KeyCode_F7           = SDLK_F7,
    KeyCode_F8           = SDLK_F8,
    KeyCode_F9           = SDLK_F9,
    KeyCode_F10          = SDLK_F10,
    KeyCode_F11          = SDLK_F11,
    KeyCode_F12          = SDLK_F12,
    // Modifiers
    KeyCode_Return       = SDLK_RETURN,
    KeyCode_Esc          = SDLK_ESCAPE,
    KeyCode_Backspace    = SDLK_BACKSPACE,
    KeyCode_Tab          = SDLK_TAB,
    KeyCode_Space        = SDLK_SPACE,
    KeyCode_PrintScreen  = SDLK_PRINTSCREEN,
    KeyCode_ScrollLock   = SDLK_SCROLLLOCK,
    KeyCode_Pause        = SDLK_PAUSE,
    KeyCode_Insert       = SDLK_INSERT,
    KeyCode_Home         = SDLK_HOME,
    KeyCode_PageUp       = SDLK_PAGEUP,
    KeyCode_PageDown     = SDLK_PAGEDOWN,
    KeyCode_Delete       = SDLK_DELETE,
    KeyCode_End          = SDLK_END,
    KeyCode_Right        = SDLK_RIGHT,
    KeyCode_Left         = SDLK_LEFT,
    KeyCode_Down         = SDLK_DOWN,
    KeyCode_Up           = SDLK_UP,
    KeyCode_Minus        = SDLK_MINUS,
    KeyCode_Equals       = SDLK_EQUALS,
    KeyCode_LeftBracket  = SDLK_LEFTBRACKET,
    KeyCode_RightBracket = SDLK_RIGHTBRACKET,
    KeyCode_BackSlash    = SDLK_BACKSLASH,
    KeyCode_SemiColon    = SDLK_SEMICOLON,
    KeyCode_Apostrophe   = SDLK_APOSTROPHE,
    KeyCode_Grave        = SDLK_GRAVE,
    KeyCode_Comma        = SDLK_COMMA,
    KeyCode_Period       = SDLK_PERIOD,
    KeyCode_Slash        = SDLK_SLASH,
    KeyCode_Capslock     = SDLK_CAPSLOCK,
    // Numpad
    KeyCode_NumLock      = SDLK_NUMLOCKCLEAR,
    KeyCode_NumDivide    = SDLK_KP_DIVIDE,
    KeyCode_NumMultiply  = SDLK_KP_MULTIPLY,
    KeyCode_NumMinus     = SDLK_KP_MINUS,
    KeyCode_NumPlus      = SDLK_KP_PLUS,
    KeyCode_NumEnter     = SDLK_KP_ENTER,
    KeyCode_NumOne       = SDLK_KP_1,
    KeyCode_NumTwo       = SDLK_KP_2,
    KeyCode_NumThree     = SDLK_KP_3,
    KeyCode_NumFour      = SDLK_KP_4,
    KeyCode_NumFive      = SDLK_KP_5,
    KeyCode_NumSix       = SDLK_KP_6,
    KeyCode_NumSeven     = SDLK_KP_7,
    KeyCode_NumEight     = SDLK_KP_8,
    KeyCode_NumNine      = SDLK_KP_9,
    KeyCode_NumZero      = SDLK_KP_0,
    KeyCode_NumPeriod    = SDLK_KP_PERIOD
} key_code_t;
