#pragma once

#include <SDL3/SDL.h>

typedef enum
{
    // Letters
    KEY_CODE_A             = SDLK_A,
    KEY_CODE_B             = SDLK_B,
    KEY_CODE_C             = SDLK_C,
    KEY_CODE_D             = SDLK_D,
    KEY_CODE_E             = SDLK_E,
    KEY_CODE_F             = SDLK_F,
    KEY_CODE_G             = SDLK_G,
    KEY_CODE_H             = SDLK_H,
    KEY_CODE_I             = SDLK_I,
    KEY_CODE_J             = SDLK_J,
    KEY_CODE_K             = SDLK_K,
    KEY_CODE_L             = SDLK_L,
    KEY_CODE_M             = SDLK_M,
    KEY_CODE_N             = SDLK_N,
    KEY_CODE_O             = SDLK_O,
    KEY_CODE_P             = SDLK_P,
    KEY_CODE_Q             = SDLK_Q,
    KEY_CODE_R             = SDLK_R,
    KEY_CODE_S             = SDLK_S,
    KEY_CODE_T             = SDLK_T,
    KEY_CODE_U             = SDLK_U,
    KEY_CODE_V             = SDLK_V,
    KEY_CODE_W             = SDLK_W,
    KEY_CODE_X             = SDLK_X,
    KEY_CODE_Y             = SDLK_Y,
    KEY_CODE_Z             = SDLK_Z,
    // Number row
    KEY_CODE_1             = SDLK_1,
    KEY_CODE_2             = SDLK_2,
    KEY_CODE_3             = SDLK_3,
    KEY_CODE_4             = SDLK_4,
    KEY_CODE_5             = SDLK_5,
    KEY_CODE_6             = SDLK_6,
    KEY_CODE_7             = SDLK_7,
    KEY_CODE_8             = SDLK_8,
    KEY_CODE_9             = SDLK_9,
    KEY_CODE_0             = SDLK_0,
    // F-row
    KEY_CODE_F1            = SDLK_F1,
    KEY_CODE_F2            = SDLK_F2,
    KEY_CODE_F3            = SDLK_F3,
    KEY_CODE_F4            = SDLK_F4,
    KEY_CODE_F5            = SDLK_F5,
    KEY_CODE_F6            = SDLK_F6,
    KEY_CODE_F7            = SDLK_F7,
    KEY_CODE_F8            = SDLK_F8,
    KEY_CODE_F9            = SDLK_F9,
    KEY_CODE_F10           = SDLK_F10,
    KEY_CODE_F11           = SDLK_F11,
    KEY_CODE_F12           = SDLK_F12,
    // Modifiers
    KEY_CODE_RETURN        = SDLK_RETURN,
    KEY_CODE_ESC           = SDLK_ESCAPE,
    KEY_CODE_BACKSPACE     = SDLK_BACKSPACE,
    KEY_CODE_TAB           = SDLK_TAB,
    KEY_CODE_SPACE         = SDLK_SPACE,
    KEY_CODE_PRIN_SCREEN   = SDLK_PRINTSCREEN,
    KEY_CODE_SCROLLLOCK    = SDLK_SCROLLLOCK,
    KEY_CODE_PAUSE         = SDLK_PAUSE,
    KEY_CODE_INSERT        = SDLK_INSERT,
    KEY_CODE_HOME          = SDLK_HOME,
    KEY_CODE_PAGE_UP       = SDLK_PAGEUP,
    KEY_CODE_PAGE_DOWN     = SDLK_PAGEDOWN,
    KEY_CODE_DELETE        = SDLK_DELETE,
    KEY_CODE_END           = SDLK_END,
    KEY_CODE_RIGHT         = SDLK_RIGHT,
    KEY_CODE_LEFT          = SDLK_LEFT,
    KEY_CODE_DOWN          = SDLK_DOWN,
    KEY_CODE_UP            = SDLK_UP,
    KEY_CODE_MINUS         = SDLK_MINUS,
    KEY_CODE_EQUALS        = SDLK_EQUALS,
    KEY_CODE_LEFT_BRACKET  = SDLK_LEFTBRACKET,
    KEY_CODE_RIGHT_BRACKET = SDLK_RIGHTBRACKET,
    KEY_CODE_BACK_SLASH    = SDLK_BACKSLASH,
    KEY_CODE_SEMI_COLON    = SDLK_SEMICOLON,
    KEY_CODE_APOSTROPHE    = SDLK_APOSTROPHE,
    KEY_CODE_GRAVE         = SDLK_GRAVE,
    KEY_CODE_COMMA         = SDLK_COMMA,
    KEY_CODE_PERIOD        = SDLK_PERIOD,
    KEY_CODE_SLASH         = SDLK_SLASH,
    KEY_CODE_CAPSLOCK      = SDLK_CAPSLOCK,
    // Numpad
    KEY_CODE_NUM_LOCK      = SDLK_NUMLOCKCLEAR,
    KEY_CODE_NUM_DIVIDE    = SDLK_KP_DIVIDE,
    KEY_CODE_NUM_MULTIPLY  = SDLK_KP_MULTIPLY,
    KEY_CODE_NUM_MINUS     = SDLK_KP_MINUS,
    KEY_CODE_NUM_PLUS      = SDLK_KP_PLUS,
    KEY_CODE_NUM_ENTER     = SDLK_KP_ENTER,
    KEY_CODE_NUM_ONE       = SDLK_KP_1,
    KEY_CODE_NUM_TWO       = SDLK_KP_2,
    KEY_CODE_NUM_THREE     = SDLK_KP_3,
    KEY_CODE_NUM_FOUR      = SDLK_KP_4,
    KEY_CODE_NUM_FIVE      = SDLK_KP_5,
    KEY_CODE_NUM_SIX       = SDLK_KP_6,
    KEY_CODE_NUM_SEVEN     = SDLK_KP_7,
    KEY_CODE_NUM_EIGHT     = SDLK_KP_8,
    KEY_CODE_NUM_NINE      = SDLK_KP_9,
    KEY_CODE_NUM_ZERO      = SDLK_KP_0,
    KEY_CODE_NUM_PERIOD    = SDLK_KP_PERIOD
} key_code_t;
