#pragma once

#include <SDL3/SDL.h>

typedef enum
{
    MOUSE_BUTTON_LEFT   = SDL_BUTTON_LEFT,
    MOUSE_BUTTON_MIDDLE = SDL_BUTTON_MIDDLE,
    MOUSE_BUTTON_RIGHT  = SDL_BUTTON_RIGHT,
    MOUSE_BUTTON_SIDE1  = SDL_BUTTON_X1,
    MOUSE_BUTTON_SIDE2  = SDL_BUTTON_X2,
} mouse_button_t;
